Pages
Bugsyaya/catalogue-bieres pull request #5
Opened 2020-10-14 07:21 UTC by CMoisan

2020-10-14 07:37 UTC, ClementineBiais approved these changes

2020-10-14 10:00 UTC, CMoisan commented
![Screenshot_1](https://user-images.githubusercontent.com/43031549/95974145-dd4edd00-0e14-11eb-833a-f4ee8e7e58ff.png)

2020-10-14 10:12 UTC, Bugsyaya requested changes

2020-10-14 10:12 UTC, Bugsyaya commented on html/biere-5.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Les links doivent être dans le `head`

2020-10-14 10:12 UTC, Bugsyaya commented on style/biere-5.css
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Doit se trouver dans le HTML (dans la balise <head></head>)

2020-10-14 10:16 UTC, CMoisan commented on html/biere-5.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Réglé

2020-10-14 10:16 UTC, CMoisan commented on style/biere-5.css
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
Réglé

2020-10-14 11:41 UTC, Bugsyaya requested changes

2020-10-14 11:41 UTC, Bugsyaya commented on html/biere-5.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
La balise <head> doit se trouver dans la balise <html>, au dessus de la balise <body>

2020-10-17 17:05 UTC, ShauniArima commented on html/biere-5.html
> +<html>
```suggestion
<!DOCTYPE html>
<html>
<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
```

2020-10-17 17:05 UTC, ShauniArima commented on html/biere-5.html
> +<html>
Should resolve https://github.com/Bugsyaya/catalogue-bieres/pull/5#discussion_r504608665 and https://github.com/Bugsyaya/catalogue-bieres/pull/5#discussion_r504608665

2025-03-24 14:52 UTC, closed without merging